### PR TITLE
Make linking with libncurses.so/dylib also bring in -ltinfo

### LINKED ISSUE #44: Linking with -lncurses should also bring in -ltinfo
In the ncurses implementation of Curses, symbols such as `cbreak` are provided by the separate tinfo library. In the old days (prior to [this transition](
https://wiki.ubuntu.com/NattyNarwhal/ToolchainTransition) or with `-flat_namespace` on the macOS linker), just listing `-lncurses` on your linker command line sufficed to bring in both libraries, but nowadays this is no longer the case if packagers do not take steps to arrange it.

In PR #10, you ultimately rejected combining libtinfo into libncurses (fair enough), and suggested that programs using libncurses should also explicitly link with libtinfo, and that providing the correct information via pkg-config suffices.

Requiring Curses-using projects to know about and link with libtinfo is reasonable for projects using autoconf macros (like AX_WITH_CURSES) or pkg-config to choose how to link Curses. It is not reasonable for projects that just have `-lcurses` or so hardcoded in their Makefiles, because if they add `-ltinfo` to their Makefiles they will no longer be portable to Curses implementations that do not have a separate tinfo library. (Note also that autoconf-archive's AX_WITH_CURSES has never implemented anything like this.)

People expect linking with solely `-lncurses` to Just Work, and the Linux distributions have arranged for this post-transition by making _libncurses.so_ actually be a linker script that brings in both libraries. Ideally conda would do so too.

As background: PR #10 was a response to #9, which was distilled from bioconda/bioconda-recipes#1391. That original samtools build failure has been reported again as samtools/samtools#940. The crux of the underlying issue is discussed in https://github.com/samtools/samtools/issues/940#issuecomment-418754819.

Conda can arrange for `-lncurses` by itself to just work by:

1. For the GNU linker (i.e., on Linux), replace the installed _libncurses.so_ with a script saying `INPUT(libncurses.so.6 -ltinfo)` and similarly for the wide versions etc.

    See e.g. 5.7-4.20100116 in the [CentOS RPM's ChangeLog](https://git.centos.org/blob/rpms!ncurses.git/c7/SPECS!ncurses.spec) for their technique.

2. On macOS, use the Darwin linker's re-exporting facilities to make libtinfo.dylib a sub-library of libncurses.dylib. For example, this could be done in your _build.sh_ by patching the generated _ncurses/Makefile_ between the configure and make steps:

```diff
--- ncurses/Makefile.orig
+++ ncurses/Makefile
@@ -129,7 +129,7 @@
 LDFLAGS		=  -Wl,-search_paths_first  
 
 SHLIB_DIRS	= -L../lib
-SHLIB_LIST	= $(SHLIB_DIRS)  -ltinfo
+SHLIB_LIST	= $(SHLIB_DIRS)  -Wl,-reexport-ltinfo
 TINFO_LIST	= $(SHLIB_DIRS) 
 TICS_LIST	= $(SHLIB_DIRS)  -ltinfo
```

This is a more palatable alternative to combining libtinfo into libncurses, but has the same effect.

### PR DESCRIPTION
**Pull request by jmarshall**
Other platforms arrange for linking with `-lncurses` to also bring in `-ltinfo` without needing the latter to be listed on the linker command line. We do so too to ease porting other software to Conda's ncurses. Fixes #44 using the techniques described there.

Implemented for macOS and for the GNU linker (i.e. Unix). Are there other platforms that this package is used on, that should be implemented too? I note the build is skipped for `[win]`.

Checklist
* [X] Used a fork of the feedstock to propose changes
* [X] Bumped the build number
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`

### CODE REVIEW

**Comment by ocefpaf** [comment]
The changes here are beyond my knowledge depth.
@isuruf can you review this one and give your expert opinion?

**Comment by jmarshall** [comment]
Ping @jakirkham @jjhelmus @isuruf? I can explain the details further if necessary — though really it's all covered in #44 and https://github.com/samtools/samtools/issues/940#issuecomment-418754819 as linked from there.

(The git conflict is merely the _meta.yaml_ build number, which has recently been bumped by 1000. I don't know the policy around such leaps, so this would be best fixed by a maintainer on merging.)

**Comment by mingwandroid** [comment]
If you want to make this change, convince upstream

**Comment by mingwandroid** [comment]
I've read the comments over at samtools, I still disagree with this change. Each .so and .dylib should autoload *only* those it actually needs.

The ncurses `.pc` file contains: `Libs:  -L${libdir} -lncursesw -ltinfow`, `pkg-config` is the de-facto cross-platform, cross-build-system way of specifying these unused-by-the-top-level-library transitive dependencies. If samtools isn't using `pkg-config` then it should be modified to use it. Fixes should always be implemented in the place of breakage, I guess this is consdered 'pragmatic' but too often the pragmatic approach causes unforseen knock-on issues.

Also, what do you do about Linux? It should suffer the same issue, and it doesn't have any such re-export capability. Here, again, if samtools used `pkg-config` then it would be a non-issue.

**Pull request merged**
