### PR TITLE
Add run_exports

### PR DESCRIPTION
**Pull request by mingwandroid**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mingwandroid** [comment]
@conda-forge-admin, please rerender

**Comment by mingwandroid** [comment]
Can we waive the license lint? https://invisible-island.net/ncurses/ncurses-license.html

**Comment by isuruf** [comment]
@conda-forge/ncurses, this is ready

**Comment by fhoehle** [comment]
@isuruf @mingwandroid thanks for your efforts!

**Review by fhoehle — APPROVED** [review]

**Pull request merged**
