### PR TITLE
Build long prefix package using conda-build 2.x

### PR DESCRIPTION
**Pull request by jjhelmus**
Fixes https://github.com/conda-forge/ncurses-feedstock/issues/25

Edit by @jakirkham : Noted fixing path length issue.

### CODE REVIEW

**Comment by jakirkham** [comment]
Could rebase on PR ( https://github.com/conda-forge/ncurses-feedstock/pull/27 ) to fix the linting issue.

**Comment by jjhelmus** [comment]
> Could rebase on PR ( #27 ) to fix the linting issue.

Done

**Comment by jakirkham** [comment]
cc @johanneskoester

**Comment by johanneskoester** [comment]
Great, thank you!

**Pull request merged**
