### PR TITLE
Remove data files

### PR DESCRIPTION
**Pull request by jschueller**
The emit warnings of file duplicates with constructor

### CODE REVIEW

**Comment by ocefpaf** [comment]
Why is this needed (or not)?

**Comment by jschueller** [comment]
@ocefpaf  It emits warnings of file duplicates when using constructor.

**Comment by ocefpaf** [comment]
> @ocefpaf It emits warnings of file duplicates when using constructor.

Are the files needed at all? If the removal of those files breaks someone workflow I'd rather deal with the warning than removing them.

**Comment by jschueller** [comment]
Indeed a subset is actually needed. Only the ducplicate one should be removed. I'm dropping this as it's very minor anyways.

**Pull request closed without merging**
