### PR TITLE
Make tests pass

### PR DESCRIPTION
**Pull request by lexual**

### CODE REVIEW

**Comment by jakirkham** [comment]
It's weird because I thought we went through this before ( https://github.com/conda-forge/ncurses-feedstock/pull/28 ), but it seems to be working this time. Not entirely sure why this is changing given `ncurses` hasn't changed. Maybe something do with `conda-build`. 😕 TBH maybe we should just allow for an optional whitespace at the end of the regex match so as to avoid this issue reoccurring the other way. After all we only care about the flags included not the trailing whitespace.

**Comment by jakirkham** [comment]
Not that I think there is anything actionable, but cc-ing @msarahan for awareness of this little oddity.

**Comment by lexual** [comment]
So it finally got built on all platforms ;)
Do we want to merge this, or do you want me to tweak test to pass if trailing whitespace or not?
Could the change in behaviour be caused by a different pkg-config perhaps??

@jakirkham @msarahan

**Comment by jakirkham** [comment]
It's a little whitespace. I don't want to get hung up on it. Just think it is strange that it changed and am unclear on whether it will again (as we don't know why it changed now). That said, am happy to merge this.

**Comment by jakirkham** [comment]
Thanks @lexual.

**Pull request merged**
